-- 
-- SQLite:
--      数据类型:
--          NULL
--          INTEGER
--          REAL
--          TEXT
--          BLOB
--      函数:
--          NULL:
--              IFNULL(X, Y)
--              IIF(X, Y, Z)
--          数值函数:
--              ROUND(X, Y)
--          文本函数:
--              SUBSTRING(X, Y)
--              REPLACE(X, Y)
--              TRIM(X)
--              LENGTH(X)
--          日期时间函数:
--              DATE(time-value, modifier, modifier, ...): YYYY-MM-DD 返回时间字符串
--              TIME(time-value, modifier, modifier, ...): HH:MM:SS 返回时间字符串
--              DATETIME(time-value, modifier, modifier, ...): YYYY-MM-DD HH:MM:SS 返回时间字符串
--              STRFTIME(format, time-value, modifier, modifier, ...)： 自定义格式 返回时间字符串
--              UNIXEPOCH(time-value, modifier, modifier, ...)
--              TIMEDIFF(time-value, time-value) 
--                  modifier:
--                      [+ / -] NNN seconds / minutes / hours / days / months / years
--                  format
--                      %Y-%m-%d %H:%M:%S: YYYY-MM-DD HH:MM:SS
--                  time-value:
--                      YYYY-MM-DD HH:MM
--                      YYYY-MM-DD HH:MM:SS
--                      YYYY-MM-DD HH:MM:SS.SSS
--                      YYYY-MM-DD
--                      HH:MM
--                      HH:MM:SS
--                      HH:MM:SS.SSS
--                      now
-- 
--          聚合函数:
--              MAX(X) / MIN(X) / AVG(X)
--              COUNT(X) / SUM(X)
--              GROUP_CONCAT(X[, Y])
-- 
--      特定用法:
--          INTEGER PRIMARY KEY AUTOINCREMENT: 自增
--      PRAGMA:
--          PRAGMA auto_vacuum = 'FULL'; -- 全自动, 允许数据库文件随着数据从数据库移除而缩小
--          PRAGMA count_changes = true; -- 获取或设置数据操作语句的返回值
--          PRAGMA synchronous = 'NORMAL'; -- NORMAL, 在关键的磁盘操作的每个序列后同步; FULL, 在每个关键的磁盘操作后同步
--          PRAGMA temp_store = 'FILE'; -- 临时文件存储, FILE / MEMORY